add:テストデータ作成
mentai-pasta/hal-platform pull request #6
Opened 2024-11-12 07:44 UTC by ohs20283

2024-11-12 08:17 UTC, Alpha9n requested changes

2024-11-12 08:17 UTC, Alpha9n commented on docker-files/database/init-files/test_mysql_init.sql
> +(07c3ce66-bda2-4e10-3752-8665cd96b26d,2024-11-5-12:00,2024-11-5-12:00,cd6c194b-aecb-8bac-c7cf-ad569ee9d5ea,'30 minutes',2024-11-10-12:00),
```suggestion
('07c3ce66-bda2-4e10-3752-8665cd96b26d','2024-11-5 12:00','2024-11-5 12:00','cd6c194b-aecb-8bac-c7cf-ad569ee9d5ea',interval'30 minutes','2024-11-10 12:00'),
```
日付の形式とクオーテーションで囲むようにするのと、intervalのところは接頭辞をつけてもらえると！！

2024-11-12 08:42 UTC, ohs20283 commented
テストデータ修正しました

2024-11-12 09:05 UTC, Alpha9n requested changes

2024-11-12 09:05 UTC, kosukej commented on docker-files/database/init-files/test_mysql_init.sql
> +INSERT INTO "vehicles" ("vehicle_id","created_at","update_at","series_id","employee_id") VALUES
```suggestion
INSERT INTO "vehicles" ("vehicle_id","created_at","updated_at","series_id","employee_id") VALUES
```

2024-11-12 09:05 UTC, kosukej commented on docker-files/database/init-files/test_mysql_init.sql
> +)
```suggestion
);
```

2024-11-12 09:05 UTC, Alpha9n commented on docker-files/database/init-files/test_mysql_init.sql
> +INSERT INTO "contacts" ("contact_id","customer_id","title","body","employee_id","created_at","update_at") VALUES
```suggestion
INSERT INTO "contacts" ("contact_id","customer_id","title","body","employee_id","created_at","updated_at") VALUES
```

2024-11-12 09:05 UTC, Alpha9n commented on docker-files/database/init-files/test_mysql_init.sql
> +('fdd25989-085e-fc11-31f0-a4a25095a47d','波留太郎','sample1@gmail.com','北海道','札幌市','1-23-4','893-1101','9f738ce8457f291b18ee47e665e96baa84f38fcd','2024-11-5-12:00','2024-11-5 12:00'),
```suggestion
('fdd25989-085e-fc11-31f0-a4a25095a47d','波留太郎','sample1@gmail.com','北海道','札幌市','1-23-4','8931101','9f738ce8457f291b18ee47e665e96baa84f38fcd','2024-11-5-12:00','2024-11-5 12:00'),
```

これはテストデータ側の不備だけど！
ハイフン消してもらえると！

2024-11-12 09:05 UTC, Alpha9n commented on docker-files/database/init-files/test_mysql_init.sql
> +INSERT INTO "customers" ("customer_id","name","email","prefecture","city","address","post_code"."password_hash","created_at","updated_at") VALUES
```suggestion
INSERT INTO "customers" ("customer_id","name","email","prefecture","city","address","post_code","password_hash","created_at","updated_at") VALUES
```

2024-11-12 12:15 UTC, Alpha9n requested changes

2024-11-12 12:15 UTC, Alpha9n commented on docker-files/database/init-files/test_mysql_init.sql
> +)
```suggestion
);
```
セミコロン抜け

2024-11-12 12:15 UTC, Alpha9n commented on docker-files/database/init-files/test_mysql_init.sql
> +('fdd25989-085e-fc11-31f0-a4a25095a47d','波留太郎','sample1@gmail.com','北海道','札幌市','1-23-4','8931101','9f738ce8457f291b18ee47e665e96baa84f38fcd','2024-11-5-12:00','2024-11-5 12:00'),
```suggestion
('fdd25989-085e-fc11-31f0-a4a25095a47d','波留太郎','sample1@gmail.com','北海道','札幌市','1-23-4','8931101','9f738ce8457f291b18ee47e665e96baa84f38fcd','2024-11-5 12:00','2024-11-5 12:00'),
```
日付の形式が異なります。

2024-11-13 08:02 UTC, tomo3101 approved these changes
![image](https://github.com/user-attachments/assets/600f5884-7de9-4b37-8722-835cccc26eb1)

2024-11-13 12:06 UTC, Alpha9n approved these changes

2024-11-13 12:11 UTC, Alpha9n commented
![LGTM](https://looks-to.me/images/posts/snn71dqanx0k5ormb9n9ray1)

2024-11-13 13:25 UTC, merged